#ifndef __ADCSMTQ_H__
#define __ADCSMTQ_H__

#include <stdint.h>

typedef enum {
    T_UINT8,
    T_INT8,
    T_UINT16,
    T_INT16,
    T_FLOAT,
    T_STRING
} ADCSMTQ_Reg_Type;

typedef struct {
    uint8_t idx;
    uint8_t data_count;
    uint8_t map_idx;
    ADCSMTQ_Reg_Type type;
} ADCSMTQ_Reg;

typedef struct {
    uint8_t port;  
} ADCSMTQ;

#define ADCSMTQ_HEAD_READ       0xC9
#define ADCSMTQ_HEAD_WRITE      0xC8

#define ADCSMTQ_RegDef          static const ADCSMTQ_Reg    

/* Register format: [idx, data_count, map_idx, type]
                idx: Denotes the register that the command will read/write from/to.
                data_count: Size of register. 4 bytes/count.
                map_idx: Determins which part of the register is being accesses; always a value from 0 to 2.
                type: Indicates the kind of data stored in a register.
*/

// Table 6-2. User Register (0)
ADCSMTQ_RegDef ADCSMTQ_REG_FACT = {  0, 1, 0, T_UINT16  };
ADCSMTQ_RegDef ADCSMTQ_REG_SNID = { 1, 3, 0, T_STRING };
ADCSMTQ_RegDef ADCSMTQ_REG_CONF = { 4, 1, 0, T_UINT8 };
ADCSMTQ_RegDef ADCSMTQ_REG_TIME = { 5, 1, 0, T_UINT8 };
ADCSMTQ_RegDef ADCSMTQ_REG_DATE = { 6, 1, 0, T_UINT8 };
ADCSMTQ_RegDef ADCSMTQ_REG_LLA_REF = { 7, 3, 0, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_Q_REF = { 10, 4, 0, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_POINTING_AXIS = { 14, 3, 0, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_TLE = { 17, 35, 0, T_STRING };
ADCSMTQ_RegDef ADCSMTQ_REG_GGA = { 52, 32, 0, T_STRING };
ADCSMTQ_RegDef ADCSMTQ_REG_ZDA = { 84, 16, 0, T_STRING };
ADCSMTQ_RegDef ADCSMTQ_REG_SV_USER = { 100, 3, 0, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_MTQ_USER = { 103, 3, 0, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG0_G_RATE_USER = { 106, 1, 0, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG0_G_TOR_USER = { 107, 1, 0, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG1_G_RATE_USER = { 108, 1, 0, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG1_G_TOR_USER = { 109, 1, 0, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG2_G_RATE_USER = { 110, 1, 0, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG2_G_TOR_USER = { 111, 1, 0, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG3_G_RATE_USER = { 112, 1, 0, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG3_G_TOR_USER = { 113, 1, 0, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_STAT = { 128, 1, 0, T_UINT8 };
ADCSMTQ_RegDef ADCSMTQ_REG_ACT_ERR = { 129, 1, 0, T_UINT8 };
ADCSMTQ_RegDef ADCSMTQ_REG_SEN_ERR = { 130, 1, 0, T_UINT8 };
ADCSMTQ_RegDef ADCSMTQ_REG_CSS_ERR = { 131, 1, 0, T_UINT8 };
ADCSMTQ_RegDef ADCSMTQ_REG_Q = { 132, 4, 0, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_RATE = { 136, 3, 0, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_LLA = { 139, 3, 0, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_ATT_ERROR = { 142, 3, 0, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_ATT_ERROR_RATE = { 145, 3, 0, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_ADCS_TMP = { 148, 1, 0, T_INT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG0_TMP = { 149, 1, 0, T_INT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG1_TMP = { 150, 1, 0, T_INT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG2_TMP = { 151, 1, 0, T_INT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG3_TMP = { 152, 1, 0, T_INT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS_TMP1 = { 153, 1, 0, T_INT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS_TMP2 = { 154, 1, 0, T_INT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS_TMP3 = { 155, 1, 0, T_INT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_SV = { 156, 3, 0, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_MAG = { 159, 3, 0, T_FLOAT };

// Table 6-3. Sensor/Actuator Register (1)
ADCSMTQ_RegDef ADCSMTQ_REG_MAG_MAT = { 0, 9, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_MAG_VEC = { 9, 3, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_MAG_STAT = { 12, 1, 1, T_UINT8 };
ADCSMTQ_RegDef ADCSMTQ_REG_MAG0_S = { 13, 3, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_MAG1_S = { 16, 3, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_MAG2_S = { 19, 3, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_MAG3_S = { 22, 3, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_MAG4_S = { 25, 3, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_MAG5_S = { 28, 3, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS_STAT = { 31, 1, 1, T_UINT8 };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS0_SV = { 32, 1, 1, T_UINT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS0_PDSUM = { 33, 1, 1, T_UINT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS1_SV = { 34, 1, 1, T_UINT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS1_PDSUM = { 35, 1, 1, T_UINT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS2_SV = { 36, 1, 1, T_UINT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS2_PDSUM = { 37, 1, 1, T_UINT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS3_SV = { 38, 1, 1, T_UINT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS3_PDSUM = { 39, 1, 1, T_UINT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS4_SV = { 40, 1, 1, T_UINT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS4_PDSUM = { 41, 1, 1, T_UINT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS5_SV = { 42, 1, 1, T_UINT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS5_PDSUM = { 43, 1, 1, T_UINT16 };
ADCSMTQ_RegDef ADCSMTQ_REG_IMU_STAT = { 44, 1, 1, T_UINT8 };
ADCSMTQ_RegDef ADCSMTQ_REG_IMU0_S = { 45, 3, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_IMU1_S = { 48, 3, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_IMU2_S = { 51, 3, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_IMU3_S = { 54, 3, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_STR_STAT = { 57, 1, 1, T_UINT8 };
ADCSMTQ_RegDef ADCSMTQ_REG_STR0_S = { 58, 4, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_STR1_S = { 62, 4, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CSS = { 66, 12, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG_STAT = { 78, 1, 1, T_UINT8 };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG0_G_ANGLE = { 79, 1, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG0_W_RATE = { 80, 1, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG1_G_ANGLE = { 81, 1, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG1_W_RATE = { 82, 1, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG2_G_ANGLE = { 83, 1, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG2_W_RATE = { 84, 1, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG3_G_ANGLE = { 85, 1, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG3_W_RATE = { 86, 1, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_MTQ = { 87, 3, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG0_G_RATE = { 90, 1, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG0_W_ACC = { 91, 1, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG1_G_RATE = { 92, 1, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG1_W_ACC = { 93, 1, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG2_G_RATE = { 94, 1, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG2_W_ACC = { 95, 1, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG3_G_RATE = { 96, 1, 1, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_CMG3_W_ACC = { 97, 1, 1, T_FLOAT };

// Table 6-4. Parameter Register (2)
ADCSMTQ_RegDef ADCSMTQ_REG_MASS = { 0, 1, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_INE_TEN = { 1, 9, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_POS_HB_B = { 10, 3, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_ORIEN_HB = { 13, 4, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_MAG_INFO = { 17, 1, 2, T_UINT8 };
ADCSMTQ_RegDef ADCSMTQ_REG_MAG0_ORIEN_BS = { 18, 4, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_MAG1_ORIEN_BS = { 22, 4, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_MAG2_ORIEN_BS = { 26, 4, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_MAG3_ORIEN_BS = { 30, 4, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_MAG4_ORIEN_BS = { 34, 4, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_MAG5_ORIEN_BS = { 38, 4, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS_INFO = { 42, 1, 2, T_UINT8 };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS0_ORIEN_BS = { 43, 4, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS1_ORIEN_BS = { 47, 4, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS2_ORIEN_BS = { 51, 4, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS3_ORIEN_BS = { 55, 4, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS4_ORIEN_BS = { 59, 4, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_FSS5_ORIEN_BS = { 63, 4, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_IMU_INFO = { 67, 1, 2, T_UINT8 };
ADCSMTQ_RegDef ADCSMTQ_REG_IMU0_ORIEN_BS = { 68, 4, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_IMU1_ORIEN_BS = { 72, 4, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_IMU2_ORIEN_BS = { 76, 4, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_IMU3_ORIEN_BS = { 80, 4, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_STR_INFO = { 84, 1, 2, T_UINT8 };
ADCSMTQ_RegDef ADCSMTQ_REG_STR0_ORIEN_BS = { 85, 4, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_STR1_ORIEN_BS = { 89, 4, 2, T_FLOAT };
ADCSMTQ_RegDef ADCSMTQ_REG_NVM = { 255, 1, 2, T_UINT8 };

// API

// Initialize ADCSMTQ object
void ADCSMTQ_init(ADCSMTQ* a, uint8_t port);
// Send register read command to ADCSMTQ
void ADCSMTQ_read_start(ADCSMTQ* a, ADCSMTQ_Reg reg);
// Handle read data received from ADCSMTQ
void ADCSMTQ_read_complete(ADCSMTQ* a, char* rcv_buf, void* data, uint8_t* status);
// Send register write command to ADCSMTQ
void ADCSMTQ_write_start(ADCSMTQ* a, ADCSMTQ_Reg reg, void* data);
// Handle write response receieved from ADCSMTQ
void ADCSMTQ_write_complete(ADCSMTQ* a, char* rcv_buf, uint8_t* status);

#endif
