//
// Copyright 2009 Tilera Corporation. All Rights Reserved.
// 
//   The source code contained or described herein and all documents
//   related to the source code ("Material") are owned by Tilera
//   Corporation or its suppliers or licensors.  Title to the Material
//   remains with Tilera Corporation or its suppliers and licensors. The
//   software is licensed under the Tilera MDE License.
// 
//   Unless otherwise agreed by Tilera in writing, you may not remove or
//   alter this notice or any other notice embedded in Materials by Tilera
//   or Tilera's suppliers or licensors in any way.
//
//

#ifndef __MAESTRO_SPR_REGS_TILE49_H
#define __MAESTRO_SPR_REGS_TILE49_H

// SPR regs from spr_constants.ent

#define SPR_MPL_ITLB_MISS_SET_0 0x0
#define SPR_MPL_ITLB_MISS_SET_1 0x1
#define SPR_MPL_ITLB_MISS_SET_2 0x2
#define SPR_MPL_ITLB_MISS_SET_3 0x3
#define SPR_MPL_ITLB_MISS 0x4
#define SPR_ITLB_CURRENT_0 0x100
#define SPR_ITLB_CURRENT_1 0x101
#define SPR_ITLB_CURRENT_2 0x102
#define SPR_ITLB_CURRENT_3 0x103
#define SPR_ITLB_INDEX 0x104
#define SPR_ITLB_MATCH_0 0x105
#define SPR_ITLB_PR 0x106
#define SPR_NUMBER_ITLB 0x107
#define SPR_REPLACEMENT_ITLB 0x108
#define SPR_WIRED_ITLB 0x109
#define SPR_MPL_MEM_ERROR_SET_0 0x200
#define SPR_MPL_MEM_ERROR_SET_1 0x201
#define SPR_MPL_MEM_ERROR_SET_2 0x202
#define SPR_MPL_MEM_ERROR_SET_3 0x203
#define SPR_MPL_MEM_ERROR 0x204
#define SPR_L1_I_ERROR 0x205
#define SPR_MEM_ERROR_CBOX_ADDR 0x206
#define SPR_MEM_ERROR_CBOX_STATUS 0x207
#define SPR_MEM_ERROR_ENABLE 0x208
#define SPR_MEM_ERROR_MBOX_ADDR 0x209
#define SPR_MEM_ERROR_MBOX_STATUS 0x20a
#define SPR_SNIC_ERROR_LOG_STATUS 0x20b
#define SPR_SNIC_ERROR_LOG_VA 0x20c
#define SPR_XDN_DEMUX_ERROR 0x20d
#define SPR_MPL_ILL_SET_0 0x400
#define SPR_MPL_ILL_SET_1 0x401
#define SPR_MPL_ILL_SET_2 0x402
#define SPR_MPL_ILL_SET_3 0x403
#define SPR_MPL_ILL 0x404
#define SPR_MPL_GPV_SET_0 0x600
#define SPR_MPL_GPV_SET_1 0x601
#define SPR_MPL_GPV_SET_2 0x602
#define SPR_MPL_GPV_SET_3 0x603
#define SPR_MPL_GPV 0x604
#define SPR_GPV_REASON 0x605
#define SPR_MPL_SN_ACCESS_SET_0 0x800
#define SPR_MPL_SN_ACCESS_SET_1 0x801
#define SPR_MPL_SN_ACCESS_SET_2 0x802
#define SPR_MPL_SN_ACCESS_SET_3 0x803
#define SPR_MPL_SN_ACCESS 0x804
#define SPR_SNCTL 0x805
#define SPR_SNFIFO_DATA 0x806
#define SPR_SNFIFO_SEL 0x807
#define SPR_SNIC_INVADDR 0x808
#define SPR_SNISTATE 0x809
#define SPR_SNOSTATE 0x80a
#define SPR_SNPC 0x80b
#define SPR_SNSTATIC 0x80c
#define SPR_SN_DATA_AVAIL 0x900
#define SPR_MPL_IDN_ACCESS_SET_0 0xa00
#define SPR_MPL_IDN_ACCESS_SET_1 0xa01
#define SPR_MPL_IDN_ACCESS_SET_2 0xa02
#define SPR_MPL_IDN_ACCESS_SET_3 0xa03
#define SPR_MPL_IDN_ACCESS 0xa04
#define SPR_IDN_DEMUX_CA_COUNT 0xa05
#define SPR_IDN_DEMUX_COUNT_0 0xa06
#define SPR_IDN_DEMUX_COUNT_1 0xa07
#define SPR_IDN_DEMUX_CTL 0xa08
#define SPR_IDN_DEMUX_CURR_TAG 0xa09
#define SPR_IDN_DEMUX_QUEUE_SEL 0xa0a
#define SPR_IDN_DEMUX_STATUS 0xa0b
#define SPR_IDN_DEMUX_WRITE_FIFO 0xa0c
#define SPR_IDN_DEMUX_WRITE_QUEUE 0xa0d
#define SPR_IDN_PENDING 0xa0e
#define SPR_IDN_SP_FIFO_DATA 0xa0f
#define SPR_IDN_SP_FIFO_SEL 0xa10
#define SPR_IDN_SP_FREEZE 0xa11
#define SPR_IDN_SP_STATE 0xa12
#define SPR_IDN_TAG_0 0xa13
#define SPR_IDN_TAG_1 0xa14
#define SPR_IDN_TAG_VALID 0xa15
#define SPR_IDN_TILE_COORD 0xa16
#define SPR_IDN_CA_DATA 0xb00
#define SPR_IDN_CA_REM 0xb01
#define SPR_IDN_CA_TAG 0xb02
#define SPR_IDN_DATA_AVAIL 0xb03
#define SPR_MPL_UDN_ACCESS_SET_0 0xc00
#define SPR_MPL_UDN_ACCESS_SET_1 0xc01
#define SPR_MPL_UDN_ACCESS_SET_2 0xc02
#define SPR_MPL_UDN_ACCESS_SET_3 0xc03
#define SPR_MPL_UDN_ACCESS 0xc04
#define SPR_UDN_DEMUX_CA_COUNT 0xc05
#define SPR_UDN_DEMUX_COUNT_0 0xc06
#define SPR_UDN_DEMUX_COUNT_1 0xc07
#define SPR_UDN_DEMUX_COUNT_2 0xc08
#define SPR_UDN_DEMUX_COUNT_3 0xc09
#define SPR_UDN_DEMUX_CTL 0xc0a
#define SPR_UDN_DEMUX_CURR_TAG 0xc0b
#define SPR_UDN_DEMUX_QUEUE_SEL 0xc0c
#define SPR_UDN_DEMUX_STATUS 0xc0d
#define SPR_UDN_DEMUX_WRITE_FIFO 0xc0e
#define SPR_UDN_DEMUX_WRITE_QUEUE 0xc0f
#define SPR_UDN_PENDING 0xc10
#define SPR_UDN_SP_FIFO_DATA 0xc11
#define SPR_UDN_SP_FIFO_SEL 0xc12
#define SPR_UDN_SP_FREEZE 0xc13
#define SPR_UDN_SP_STATE 0xc14
#define SPR_UDN_TAG_0 0xc15
#define SPR_UDN_TAG_1 0xc16
#define SPR_UDN_TAG_2 0xc17
#define SPR_UDN_TAG_3 0xc18
#define SPR_UDN_TAG_VALID 0xc19
#define SPR_UDN_TILE_COORD 0xc1a
#define SPR_UDN_CA_DATA 0xd00
#define SPR_UDN_CA_REM 0xd01
#define SPR_UDN_CA_TAG 0xd02
#define SPR_UDN_DATA_AVAIL 0xd03
#define SPR_MPL_IDN_REFILL_SET_0 0xe00
#define SPR_MPL_IDN_REFILL_SET_1 0xe01
#define SPR_MPL_IDN_REFILL_SET_2 0xe02
#define SPR_MPL_IDN_REFILL_SET_3 0xe03
#define SPR_MPL_IDN_REFILL 0xe04
#define SPR_IDN_REFILL_EN 0xe05
#define SPR_MPL_UDN_REFILL_SET_0 0x1000
#define SPR_MPL_UDN_REFILL_SET_1 0x1001
#define SPR_MPL_UDN_REFILL_SET_2 0x1002
#define SPR_MPL_UDN_REFILL_SET_3 0x1003
#define SPR_MPL_UDN_REFILL 0x1004
#define SPR_UDN_REFILL_EN 0x1005
#define SPR_MPL_IDN_COMPLETE_SET_0 0x1200
#define SPR_MPL_IDN_COMPLETE_SET_1 0x1201
#define SPR_MPL_IDN_COMPLETE_SET_2 0x1202
#define SPR_MPL_IDN_COMPLETE_SET_3 0x1203
#define SPR_MPL_IDN_COMPLETE 0x1204
#define SPR_IDN_REMAINING 0x1205
#define SPR_MPL_UDN_COMPLETE_SET_0 0x1400
#define SPR_MPL_UDN_COMPLETE_SET_1 0x1401
#define SPR_MPL_UDN_COMPLETE_SET_2 0x1402
#define SPR_MPL_UDN_COMPLETE_SET_3 0x1403
#define SPR_MPL_UDN_COMPLETE 0x1404
#define SPR_UDN_REMAINING 0x1405
#define SPR_MPL_SWINT_3_SET_0 0x1600
#define SPR_MPL_SWINT_3_SET_1 0x1601
#define SPR_MPL_SWINT_3_SET_2 0x1602
#define SPR_MPL_SWINT_3_SET_3 0x1603
#define SPR_MPL_SWINT_3 0x1604
#define SPR_MPL_SWINT_2_SET_0 0x1800
#define SPR_MPL_SWINT_2_SET_1 0x1801
#define SPR_MPL_SWINT_2_SET_2 0x1802
#define SPR_MPL_SWINT_2_SET_3 0x1803
#define SPR_MPL_SWINT_2 0x1804
#define SPR_MPL_SWINT_1_SET_0 0x1a00
#define SPR_MPL_SWINT_1_SET_1 0x1a01
#define SPR_MPL_SWINT_1_SET_2 0x1a02
#define SPR_MPL_SWINT_1_SET_3 0x1a03
#define SPR_MPL_SWINT_1 0x1a04
#define SPR_MPL_SWINT_0_SET_0 0x1c00
#define SPR_MPL_SWINT_0_SET_1 0x1c01
#define SPR_MPL_SWINT_0_SET_2 0x1c02
#define SPR_MPL_SWINT_0_SET_3 0x1c03
#define SPR_MPL_SWINT_0 0x1c04
#define SPR_MPL_UNALIGN_DATA_SET_0 0x1e00
#define SPR_MPL_UNALIGN_DATA_SET_1 0x1e01
#define SPR_MPL_UNALIGN_DATA_SET_2 0x1e02
#define SPR_MPL_UNALIGN_DATA_SET_3 0x1e03
#define SPR_MPL_UNALIGN_DATA 0x1e04
#define SPR_MPL_DTLB_MISS_SET_0 0x2000
#define SPR_MPL_DTLB_MISS_SET_1 0x2001
#define SPR_MPL_DTLB_MISS_SET_2 0x2002
#define SPR_MPL_DTLB_MISS_SET_3 0x2003
#define SPR_MPL_DTLB_MISS 0x2004
#define SPR_AER_0 0x2100
#define SPR_AER_1 0x2101
#define SPR_DTLB_BAD_ADDR 0x2102
#define SPR_DTLB_BAD_ADDR_REASON 0x2103
#define SPR_DTLB_CURRENT_0 0x2104
#define SPR_DTLB_CURRENT_1 0x2105
#define SPR_DTLB_CURRENT_2 0x2106
#define SPR_DTLB_CURRENT_3 0x2107
#define SPR_DTLB_INDEX 0x2108
#define SPR_DTLB_MATCH_0 0x2109
#define SPR_NUMBER_DTLB 0x210a
#define SPR_PHYSICAL_MEMORY_MODE 0x210b
#define SPR_REPLACEMENT_DTLB 0x210c
#define SPR_WIRED_DTLB 0x210d
#define SPR_MPL_DTLB_ACCESS_SET_0 0x2200
#define SPR_MPL_DTLB_ACCESS_SET_1 0x2201
#define SPR_MPL_DTLB_ACCESS_SET_2 0x2202
#define SPR_MPL_DTLB_ACCESS_SET_3 0x2203
#define SPR_MPL_DTLB_ACCESS 0x2204
#define SPR_MPL_DMATLB_MISS_SET_0 0x2400
#define SPR_MPL_DMATLB_MISS_SET_1 0x2401
#define SPR_MPL_DMATLB_MISS_SET_2 0x2402
#define SPR_MPL_DMATLB_MISS_SET_3 0x2403
#define SPR_MPL_DMATLB_MISS 0x2404
#define SPR_DMA_BAD_ADDR 0x2500
#define SPR_DMA_STATUS 0x2501
#define SPR_MPL_DMATLB_ACCESS_SET_0 0x2600
#define SPR_MPL_DMATLB_ACCESS_SET_1 0x2601
#define SPR_MPL_DMATLB_ACCESS_SET_2 0x2602
#define SPR_MPL_DMATLB_ACCESS_SET_3 0x2603
#define SPR_MPL_DMATLB_ACCESS 0x2604
#define SPR_MPL_SNITLB_MISS_SET_0 0x2800
#define SPR_MPL_SNITLB_MISS_SET_1 0x2801
#define SPR_MPL_SNITLB_MISS_SET_2 0x2802
#define SPR_MPL_SNITLB_MISS_SET_3 0x2803
#define SPR_MPL_SNITLB_MISS 0x2804
#define SPR_NUMBER_SNITLB 0x2805
#define SPR_REPLACEMENT_SNITLB 0x2806
#define SPR_SNITLB_CURRENT_0 0x2807
#define SPR_SNITLB_CURRENT_1 0x2808
#define SPR_SNITLB_CURRENT_2 0x2809
#define SPR_SNITLB_CURRENT_3 0x280a
#define SPR_SNITLB_INDEX 0x280b
#define SPR_SNITLB_MATCH_0 0x280c
#define SPR_SNITLB_PR 0x280d
#define SPR_WIRED_SNITLB 0x280e
#define SPR_SNITLB_STATUS 0x280f
#define SPR_MPL_SN_NOTIFY_SET_0 0x2a00
#define SPR_MPL_SN_NOTIFY_SET_1 0x2a01
#define SPR_MPL_SN_NOTIFY_SET_2 0x2a02
#define SPR_MPL_SN_NOTIFY_SET_3 0x2a03
#define SPR_MPL_SN_NOTIFY 0x2a04
#define SPR_SN_NOTIFY_STATUS 0x2a05
#define SPR_MPL_SN_FIREWALL_SET_0 0x2c00
#define SPR_MPL_SN_FIREWALL_SET_1 0x2c01
#define SPR_MPL_SN_FIREWALL_SET_2 0x2c02
#define SPR_MPL_SN_FIREWALL_SET_3 0x2c03
#define SPR_MPL_SN_FIREWALL 0x2c04
#define SPR_SN_DIRECTION_PROTECT 0x2c05
#define SPR_MPL_IDN_FIREWALL_SET_0 0x2e00
#define SPR_MPL_IDN_FIREWALL_SET_1 0x2e01
#define SPR_MPL_IDN_FIREWALL_SET_2 0x2e02
#define SPR_MPL_IDN_FIREWALL_SET_3 0x2e03
#define SPR_MPL_IDN_FIREWALL 0x2e04
#define SPR_IDN_DIRECTION_PROTECT 0x2e05
#define SPR_MPL_UDN_FIREWALL_SET_0 0x3000
#define SPR_MPL_UDN_FIREWALL_SET_1 0x3001
#define SPR_MPL_UDN_FIREWALL_SET_2 0x3002
#define SPR_MPL_UDN_FIREWALL_SET_3 0x3003
#define SPR_MPL_UDN_FIREWALL 0x3004
#define SPR_UDN_DIRECTION_PROTECT 0x3005
#define SPR_MPL_TILE_TIMER_SET_0 0x3200
#define SPR_MPL_TILE_TIMER_SET_1 0x3201
#define SPR_MPL_TILE_TIMER_SET_2 0x3202
#define SPR_MPL_TILE_TIMER_SET_3 0x3203
#define SPR_MPL_TILE_TIMER 0x3204
#define SPR_TILE_TIMER_CONTROL 0x3205
#define SPR_MPL_IDN_TIMER_SET_0 0x3400
#define SPR_MPL_IDN_TIMER_SET_1 0x3401
#define SPR_MPL_IDN_TIMER_SET_2 0x3402
#define SPR_MPL_IDN_TIMER_SET_3 0x3403
#define SPR_MPL_IDN_TIMER 0x3404
#define SPR_IDN_DEADLOCK_COUNT 0x3405
#define SPR_IDN_DEADLOCK_TIMEOUT 0x3406
#define SPR_MPL_UDN_TIMER_SET_0 0x3600
#define SPR_MPL_UDN_TIMER_SET_1 0x3601
#define SPR_MPL_UDN_TIMER_SET_2 0x3602
#define SPR_MPL_UDN_TIMER_SET_3 0x3603
#define SPR_MPL_UDN_TIMER 0x3604
#define SPR_UDN_DEADLOCK_COUNT 0x3605
#define SPR_UDN_DEADLOCK_TIMEOUT 0x3606
#define SPR_MPL_DMA_NOTIFY_SET_0 0x3800
#define SPR_MPL_DMA_NOTIFY_SET_1 0x3801
#define SPR_MPL_DMA_NOTIFY_SET_2 0x3802
#define SPR_MPL_DMA_NOTIFY_SET_3 0x3803
#define SPR_MPL_DMA_NOTIFY 0x3804
#define SPR_DMA_BYTE 0x3900
#define SPR_DMA_CHUNK_SIZE 0x3901
#define SPR_DMA_CTR 0x3902
#define SPR_DMA_DST_ADDR 0x3903
#define SPR_DMA_DST_CHUNK_ADDR 0x3904
#define SPR_DMA_SRC_ADDR 0x3905
#define SPR_DMA_SRC_CHUNK_ADDR 0x3906
#define SPR_DMA_STRIDE 0x3907
#define SPR_DMA_USER_STATUS 0x3908
#define SPR_MPL_IDN_CA_SET_0 0x3a00
#define SPR_MPL_IDN_CA_SET_1 0x3a01
#define SPR_MPL_IDN_CA_SET_2 0x3a02
#define SPR_MPL_IDN_CA_SET_3 0x3a03
#define SPR_MPL_IDN_CA 0x3a04
#define SPR_MPL_UDN_CA_SET_0 0x3c00
#define SPR_MPL_UDN_CA_SET_1 0x3c01
#define SPR_MPL_UDN_CA_SET_2 0x3c02
#define SPR_MPL_UDN_CA_SET_3 0x3c03
#define SPR_MPL_UDN_CA 0x3c04
#define SPR_MPL_IDN_AVAIL_SET_0 0x3e00
#define SPR_MPL_IDN_AVAIL_SET_1 0x3e01
#define SPR_MPL_IDN_AVAIL_SET_2 0x3e02
#define SPR_MPL_IDN_AVAIL_SET_3 0x3e03
#define SPR_MPL_IDN_AVAIL 0x3e04
#define SPR_IDN_AVAIL_EN 0x3e05
#define SPR_MPL_UDN_AVAIL_SET_0 0x4000
#define SPR_MPL_UDN_AVAIL_SET_1 0x4001
#define SPR_MPL_UDN_AVAIL_SET_2 0x4002
#define SPR_MPL_UDN_AVAIL_SET_3 0x4003
#define SPR_MPL_UDN_AVAIL 0x4004
#define SPR_UDN_AVAIL_EN 0x4005
#define SPR_MPL_PERF_COUNT_SET_0 0x4200
#define SPR_MPL_PERF_COUNT_SET_1 0x4201
#define SPR_MPL_PERF_COUNT_SET_2 0x4202
#define SPR_MPL_PERF_COUNT_SET_3 0x4203
#define SPR_MPL_PERF_COUNT 0x4204
#define SPR_PERF_COUNT_0 0x4205
#define SPR_PERF_COUNT_1 0x4206
#define SPR_PERF_COUNT_CTL 0x4207
#define SPR_PERF_COUNT_STS 0x4208
#define SPR_WATCH_CTL 0x4209
#define SPR_WATCH_MASK 0x420a
#define SPR_WATCH_VAL 0x420b
#define SPR_MPL_INTCTRL_3_SET_0 0x4400
#define SPR_MPL_INTCTRL_3_SET_1 0x4401
#define SPR_MPL_INTCTRL_3_SET_2 0x4402
#define SPR_MPL_INTCTRL_3_SET_3 0x4403
#define SPR_MPL_INTCTRL_3 0x4404
#define SPR_EX_CONTEXT_3_0 0x4405
#define SPR_EX_CONTEXT_3_1 0x4406
#define SPR_INTERRUPT_MASK_3_0 0x4407
#define SPR_INTERRUPT_MASK_3_1 0x4408
#define SPR_INTERRUPT_MASK_RESET_3_0 0x4409
#define SPR_INTERRUPT_MASK_RESET_3_1 0x440a
#define SPR_INTERRUPT_MASK_SET_3_0 0x440b
#define SPR_INTERRUPT_MASK_SET_3_1 0x440c
#define SPR_SYSTEM_SAVE_3_0 0x4500
#define SPR_SYSTEM_SAVE_3_1 0x4501
#define SPR_SYSTEM_SAVE_3_2 0x4502
#define SPR_SYSTEM_SAVE_3_3 0x4503
#define SPR_MPL_INTCTRL_2_SET_0 0x4600
#define SPR_MPL_INTCTRL_2_SET_1 0x4601
#define SPR_MPL_INTCTRL_2_SET_2 0x4602
#define SPR_MPL_INTCTRL_2_SET_3 0x4603
#define SPR_MPL_INTCTRL_2 0x4604
#define SPR_EX_CONTEXT_2_0 0x4605
#define SPR_EX_CONTEXT_2_1 0x4606
#define SPR_INTCTRL_2_STATUS 0x4607
#define SPR_INTERRUPT_MASK_2_0 0x4608
#define SPR_INTERRUPT_MASK_2_1 0x4609
#define SPR_INTERRUPT_MASK_RESET_2_0 0x460a
#define SPR_INTERRUPT_MASK_RESET_2_1 0x460b
#define SPR_INTERRUPT_MASK_SET_2_0 0x460c
#define SPR_INTERRUPT_MASK_SET_2_1 0x460d
#define SPR_SYSTEM_SAVE_2_0 0x4700
#define SPR_SYSTEM_SAVE_2_1 0x4701
#define SPR_SYSTEM_SAVE_2_2 0x4702
#define SPR_SYSTEM_SAVE_2_3 0x4703
#define SPR_MPL_INTCTRL_1_SET_0 0x4800
#define SPR_MPL_INTCTRL_1_SET_1 0x4801
#define SPR_MPL_INTCTRL_1_SET_2 0x4802
#define SPR_MPL_INTCTRL_1_SET_3 0x4803
#define SPR_MPL_INTCTRL_1 0x4804
#define SPR_EX_CONTEXT_1_0 0x4805
#define SPR_EX_CONTEXT_1_1 0x4806
#define SPR_INTCTRL_1_STATUS 0x4807
#define SPR_INTCTRL_3_STATUS 0x4808
#define SPR_INTERRUPT_MASK_1_0 0x4809
#define SPR_INTERRUPT_MASK_1_1 0x480a
#define SPR_INTERRUPT_MASK_RESET_1_0 0x480b
#define SPR_INTERRUPT_MASK_RESET_1_1 0x480c
#define SPR_INTERRUPT_MASK_SET_1_0 0x480d
#define SPR_INTERRUPT_MASK_SET_1_1 0x480e
#define SPR_SYSTEM_SAVE_1_0 0x4900
#define SPR_SYSTEM_SAVE_1_1 0x4901
#define SPR_SYSTEM_SAVE_1_2 0x4902
#define SPR_SYSTEM_SAVE_1_3 0x4903
#define SPR_MPL_INTCTRL_0_SET_0 0x4a00
#define SPR_MPL_INTCTRL_0_SET_1 0x4a01
#define SPR_MPL_INTCTRL_0_SET_2 0x4a02
#define SPR_MPL_INTCTRL_0_SET_3 0x4a03
#define SPR_MPL_INTCTRL_0 0x4a04
#define SPR_EX_CONTEXT_0_0 0x4a05
#define SPR_EX_CONTEXT_0_1 0x4a06
#define SPR_INTCTRL_0_STATUS 0x4a07
#define SPR_INTERRUPT_MASK_0_0 0x4a08
#define SPR_INTERRUPT_MASK_0_1 0x4a09
#define SPR_INTERRUPT_MASK_RESET_0_0 0x4a0a
#define SPR_INTERRUPT_MASK_RESET_0_1 0x4a0b
#define SPR_INTERRUPT_MASK_SET_0_0 0x4a0c
#define SPR_INTERRUPT_MASK_SET_0_1 0x4a0d
#define SPR_SYSTEM_SAVE_0_0 0x4b00
#define SPR_SYSTEM_SAVE_0_1 0x4b01
#define SPR_SYSTEM_SAVE_0_2 0x4b02
#define SPR_SYSTEM_SAVE_0_3 0x4b03
#define SPR_MPL_BOOT_ACCESS_SET_0 0x4c00
#define SPR_MPL_BOOT_ACCESS_SET_1 0x4c01
#define SPR_MPL_BOOT_ACCESS_SET_2 0x4c02
#define SPR_MPL_BOOT_ACCESS_SET_3 0x4c03
#define SPR_MPL_BOOT_ACCESS 0x4c04
#define SPR_CBOX_CACHEASRAM_CONFIG 0x4c05
#define SPR_CBOX_CACHE_CONFIG 0x4c06
#define SPR_CBOX_MMAP_0 0x4c07
#define SPR_CBOX_MMAP_1 0x4c08
#define SPR_CBOX_MMAP_2 0x4c09
#define SPR_CBOX_MMAP_3 0x4c0a
#define SPR_CBOX_MSR 0x4c0b
#define SPR_CBOX_SRC_ID 0x4c0c
#define SPR_CYCLE_HIGH_MODIFY 0x4c0d
#define SPR_CYCLE_LOW_MODIFY 0x4c0e
#define SPR_DIAG_BCST_CTL 0x4c0f
#define SPR_DIAG_BCST_MASK 0x4c10
#define SPR_DIAG_BCST_TRIGGER 0x4c11
#define SPR_DIAG_MUX_CTL 0x4c12
#define SPR_DIAG_TRACE_CTL 0x4c13
#define SPR_DIAG_TRACE_STS 0x4c14
#define SPR_IDN_DEMUX_BUF_THRESH 0x4c15
#define SPR_SBOX_CONFIG 0x4c16
#define SPR_TILE_COORD 0x4c17
#define SPR_UDN_DEMUX_BUF_THRESH 0x4c18
#define SPR_I_AER_0 0x4d00
#define SPR_I_AER_1 0x4d01
#define SPR_I_PHYSICAL_MEMORY_MODE 0x4d02
#define SPR_MPL_WORLD_ACCESS_SET_0 0x4e00
#define SPR_MPL_WORLD_ACCESS_SET_1 0x4e01
#define SPR_MPL_WORLD_ACCESS_SET_2 0x4e02
#define SPR_MPL_WORLD_ACCESS_SET_3 0x4e03
#define SPR_MPL_WORLD_ACCESS 0x4e04
#define SPR_BREAKPOINT 0x4e05
#define SPR_CYCLE_HIGH 0x4e06
#define SPR_CYCLE_LOW 0x4e07
#define SPR_DONE 0x4e08
#define SPR_FAIL 0x4e09
#define SPR_INTERRUPT_CRITICAL_SECTION 0x4e0a
#define SPR_PASS 0x4e0b
#define SPR_SIM_CONTROL 0x4e0c
#define SPR_EVENT_BEGIN 0x4e0d
#define SPR_EVENT_END 0x4e0e
#define SPR_MPL_I_ASID_SET_0 0x5000
#define SPR_MPL_I_ASID_SET_1 0x5001
#define SPR_MPL_I_ASID_SET_2 0x5002
#define SPR_MPL_I_ASID_SET_3 0x5003
#define SPR_MPL_I_ASID 0x5004
#define SPR_I_ASID 0x5005
#define SPR_MPL_D_ASID_SET_0 0x5200
#define SPR_MPL_D_ASID_SET_1 0x5201
#define SPR_MPL_D_ASID_SET_2 0x5202
#define SPR_MPL_D_ASID_SET_3 0x5203
#define SPR_MPL_D_ASID 0x5204
#define SPR_D_ASID 0x5205
#define SPR_MPL_DMA_ASID_SET_0 0x5400
#define SPR_MPL_DMA_ASID_SET_1 0x5401
#define SPR_MPL_DMA_ASID_SET_2 0x5402
#define SPR_MPL_DMA_ASID_SET_3 0x5403
#define SPR_MPL_DMA_ASID 0x5404
#define SPR_DMA_ASID 0x5405
#define SPR_MPL_SNI_ASID_SET_0 0x5600
#define SPR_MPL_SNI_ASID_SET_1 0x5601
#define SPR_MPL_SNI_ASID_SET_2 0x5602
#define SPR_MPL_SNI_ASID_SET_3 0x5603
#define SPR_MPL_SNI_ASID 0x5604
#define SPR_SNI_ASID 0x5605
#define SPR_MPL_DMA_CPL_SET_0 0x5800
#define SPR_MPL_DMA_CPL_SET_1 0x5801
#define SPR_MPL_DMA_CPL_SET_2 0x5802
#define SPR_MPL_DMA_CPL_SET_3 0x5803
#define SPR_MPL_DMA_CPL 0x5804
#define SPR_MPL_SN_CPL_SET_0 0x5a00
#define SPR_MPL_SN_CPL_SET_1 0x5a01
#define SPR_MPL_SN_CPL_SET_2 0x5a02
#define SPR_MPL_SN_CPL_SET_3 0x5a03
#define SPR_MPL_SN_CPL 0x5a04
#define SPR_MPL_DOUBLE_FAULT_SET_0 0x5c00
#define SPR_MPL_DOUBLE_FAULT_SET_1 0x5c01
#define SPR_MPL_DOUBLE_FAULT_SET_2 0x5c02
#define SPR_MPL_DOUBLE_FAULT_SET_3 0x5c03
#define SPR_MPL_DOUBLE_FAULT 0x5c04
#define SPR_LAST_INTERRUPT_REASON 0x5c05

/*
 * TODO: How is this used?
fast_spr_list [
    SPR_IDN_DATA_AVAIL,
    SPR_IDN_CA_TAG,
    SPR_IDN_CA_REM,
    SPR_IDN_CA_DATA,    
    SPR_DMA_CTR,
    SPR_DMA_STRIDE,
    SPR_DMA_CHUNK_SIZE,
    SPR_DMA_SRC_CHUNK_ADDR,
    SPR_DMA_SRC_ADDR,
    SPR_DMA_DST_CHUNK_ADDR,
    SPR_DMA_DST_ADDR,
    SPR_DMA_BYTE,
    SPR_DMA_STATUS,
    SPR_DMA_USER_STATUS,
    SPR_DMA_BAD_ADDR,
    SPR_SYSTEM_SAVE_0_0,
    SPR_SYSTEM_SAVE_0_1,
    SPR_SYSTEM_SAVE_0_2,
    SPR_SYSTEM_SAVE_0_3,
    SPR_SYSTEM_SAVE_1_0,
    SPR_SYSTEM_SAVE_1_1,
    SPR_SYSTEM_SAVE_1_2,
    SPR_SYSTEM_SAVE_1_3,
    SPR_SYSTEM_SAVE_2_0,
    SPR_SYSTEM_SAVE_2_1,
    SPR_SYSTEM_SAVE_2_2,
    SPR_SYSTEM_SAVE_2_3,
    SPR_SYSTEM_SAVE_3_0,
    SPR_SYSTEM_SAVE_3_1,
    SPR_SYSTEM_SAVE_3_2,
    SPR_SYSTEM_SAVE_3_3,
    SPR_ITLB_CURRENT_0,
    SPR_ITLB_CURRENT_1,
    SPR_ITLB_CURRENT_2,
    SPR_ITLB_CURRENT_3,
    SPR_ITLB_INDEX,
    SPR_WIRED_ITLB,
    SPR_REPLACEMENT_ITLB,
    SPR_NUMBER_ITLB,
    SPR_ITLB_PR,
    SPR_ITLB_MATCH_0,
    SPR_I_PHYSICAL_MEMORY_MODE,
    SPR_I_AER_0,
    SPR_I_AER_1,
    SPR_PHYSICAL_MEMORY_MODE,
    SPR_AER_0,
    SPR_AER_1,
    SPR_DTLB_CURRENT_0,
    SPR_DTLB_CURRENT_1,
    SPR_DTLB_CURRENT_2,
    SPR_DTLB_CURRENT_3,
    SPR_DTLB_INDEX,
    SPR_WIRED_DTLB,
    SPR_REPLACEMENT_DTLB,
    SPR_NUMBER_DTLB,
    SPR_DTLB_MATCH_0,
    SPR_DTLB_BAD_ADDR,
    SPR_DTLB_BAD_ADDR_REASON,
    SPR_SN_DATA_AVAIL,
    SPR_UDN_DATA_AVAIL,
    SPR_UDN_CA_TAG,
    SPR_UDN_CA_REM,
    SPR_UDN_CA_DATA
    ]
 */

// Diag registers from diag.vh
#define DIAG_TOP_WIDTH 32

#define DIAG_TOP_MODE3_BYTES 4
#define DIAG_TOP_MODE3_PASS_LSB 0
#define DIAG_TOP_MODE3_PASS_MSB 31

#define DIAG_TOP_MODE2_BYTES 4
#define DIAG_TOP_MODE2_PASS_LSB 0
#define DIAG_TOP_MODE2_PASS_MSB 31

#define DIAG_TOP_MODE1_BYTES 1
#define DIAG_TOP_MODE1_FAIL_WRITTEN_LSB 0
#define DIAG_TOP_MODE1_FAIL_WRITTEN_MSB 0
#define DIAG_TOP_MODE1_DONE_WRITTEN_LSB 1
#define DIAG_TOP_MODE1_DONE_WRITTEN_MSB 1
#define DIAG_TOP_MODE1_QUIESCED_LSB 2
#define DIAG_TOP_MODE1_QUIESCED_MSB 2
#define DIAG_TOP_MODE1_ONE_LSB 3
#define DIAG_TOP_MODE1_ONE_MSB 3
#define DIAG_TOP_MODE1_PASS_LSB 4
#define DIAG_TOP_MODE1_PASS_MSB 7

#define DIAG_TOP_MODE0_BYTES 0


#define DIAG_SBOX_WIDTH 144

#define DIAG_SBOX_MODE3_BYTES 18
#define DIAG_SBOX_MODE3_INSTRUCTION_VALID_IF_LSB 0
#define DIAG_SBOX_MODE3_INSTRUCTION_VALID_IF_MSB 0
#define DIAG_SBOX_MODE3_INSTRUCTION_VALID_RF_LSB 1
#define DIAG_SBOX_MODE3_INSTRUCTION_VALID_RF_MSB 1
#define DIAG_SBOX_MODE3_INSTRUCTION_VALID_P0_P1_EX0_LSB 2
#define DIAG_SBOX_MODE3_INSTRUCTION_VALID_P0_P1_EX0_MSB 2
#define DIAG_SBOX_MODE3_INSTRUCTION_VALID_P0_P1_EX1_LSB 3
#define DIAG_SBOX_MODE3_INSTRUCTION_VALID_P0_P1_EX1_MSB 3
#define DIAG_SBOX_MODE3_FRONT_END_RESTART_EX0_D1_LSB 4
#define DIAG_SBOX_MODE3_FRONT_END_RESTART_EX0_D1_MSB 4
#define DIAG_SBOX_MODE3_FRONT_END_RESTART_EX1_D1_LSB 5
#define DIAG_SBOX_MODE3_FRONT_END_RESTART_EX1_D1_MSB 5
#define DIAG_SBOX_MODE3_KILL_PREVIOUS_NO_ROLLBACK_EX1_LSB 6
#define DIAG_SBOX_MODE3_KILL_PREVIOUS_NO_ROLLBACK_EX1_MSB 6
#define DIAG_SBOX_MODE3_KILL_PREVIOUS_WITH_ROLLBACK_EX1_LSB 7
#define DIAG_SBOX_MODE3_KILL_PREVIOUS_WITH_ROLLBACK_EX1_MSB 7
#define DIAG_SBOX_MODE3_KILL_EX1_LSB 8
#define DIAG_SBOX_MODE3_KILL_EX1_MSB 8
#define DIAG_SBOX_MODE3_FETCH_PC_LSB 9
#define DIAG_SBOX_MODE3_FETCH_PC_MSB 37
#define DIAG_SBOX_MODE3_REGISTER_RAW_STALL_D1_LSB 38
#define DIAG_SBOX_MODE3_REGISTER_RAW_STALL_D1_MSB 38
#define DIAG_SBOX_MODE3_CA_READ_STALL_D1_LSB 39
#define DIAG_SBOX_MODE3_CA_READ_STALL_D1_MSB 39
#define DIAG_SBOX_MODE3_LOAD_WAW_STALL_D1_LSB 40
#define DIAG_SBOX_MODE3_LOAD_WAW_STALL_D1_MSB 40
#define DIAG_SBOX_MODE3_NETWORK_LOAD_OPERATION_WAW_STALL_D1_LSB 41
#define DIAG_SBOX_MODE3_NETWORK_LOAD_OPERATION_WAW_STALL_D1_MSB 41
#define DIAG_SBOX_MODE3_MEMORY_OPERATION_COLLISION_OR_RETURNING_LOAD_ALIAS_STALL_D1_LSB 42
#define DIAG_SBOX_MODE3_MEMORY_OPERATION_COLLISION_OR_RETURNING_LOAD_ALIAS_STALL_D1_MSB 42
#define DIAG_SBOX_MODE3_NETWORK_FULL_STALL_D1_LSB 43
#define DIAG_SBOX_MODE3_NETWORK_FULL_STALL_D1_MSB 43
#define DIAG_SBOX_MODE3_TLB_HAZZARD_STALL_D1_LSB 44
#define DIAG_SBOX_MODE3_TLB_HAZZARD_STALL_D1_MSB 44
#define DIAG_SBOX_MODE3_MF_STALL_D1_LSB 45
#define DIAG_SBOX_MODE3_MF_STALL_D1_MSB 45
#define DIAG_SBOX_MODE3_SLOW_SPR_STALL_D1_LSB 46
#define DIAG_SBOX_MODE3_SLOW_SPR_STALL_D1_MSB 46
#define DIAG_SBOX_MODE3_OVERRIDE_INTERNAL_STALL_D1_LSB 47
#define DIAG_SBOX_MODE3_OVERRIDE_INTERNAL_STALL_D1_MSB 47
#define DIAG_SBOX_MODE3_ITLB_MISS_EX0_LSB 48
#define DIAG_SBOX_MODE3_ITLB_MISS_EX0_MSB 48
#define DIAG_SBOX_MODE3_ICACHE_TAG_MISS_EX0_LSB 49
#define DIAG_SBOX_MODE3_ICACHE_TAG_MISS_EX0_MSB 49
#define DIAG_SBOX_MODE3_LOAD_MISS_REPLAY_EX1_LSB 50
#define DIAG_SBOX_MODE3_LOAD_MISS_REPLAY_EX1_MSB 50
#define DIAG_SBOX_MODE3_CONDITIONAL_MISSPREDICT_EX1_LSB 51
#define DIAG_SBOX_MODE3_CONDITIONAL_MISSPREDICT_EX1_MSB 51
#define DIAG_SBOX_MODE3_JR_MISPREDICT_EX1_LSB 52
#define DIAG_SBOX_MODE3_JR_MISPREDICT_EX1_MSB 52
#define DIAG_SBOX_MODE3_UNCONDITIONAL_MISPREDICT_EX1_LSB 53
#define DIAG_SBOX_MODE3_UNCONDITIONAL_MISPREDICT_EX1_MSB 53
#define DIAG_SBOX_MODE3_MEMORY_BUBBLE_RF_D1_LSB 54
#define DIAG_SBOX_MODE3_MEMORY_BUBBLE_RF_D1_MSB 54
#define DIAG_SBOX_MODE3_PRECONDITIONED_INTERRUPT_SIGNALED_EX1_LSB 55
#define DIAG_SBOX_MODE3_PRECONDITIONED_INTERRUPT_SIGNALED_EX1_MSB 55
#define DIAG_SBOX_MODE3_INTERRUPT_SIGNALED_EX1_D1_LSB 56
#define DIAG_SBOX_MODE3_INTERRUPT_SIGNALED_EX1_D1_MSB 56
#define DIAG_SBOX_MODE3_IFILL_RETURN_IF_LSB 57
#define DIAG_SBOX_MODE3_IFILL_RETURN_IF_MSB 57
#define DIAG_SBOX_MODE3_FETCH_STATE_LSB 58
#define DIAG_SBOX_MODE3_FETCH_STATE_MSB 63
#define DIAG_SBOX_MODE3_FILL_STATE_LSB 64
#define DIAG_SBOX_MODE3_FILL_STATE_MSB 67
#define DIAG_SBOX_MODE3_CMDUEST_DEMAND_IFILL_RF_LSB 68
#define DIAG_SBOX_MODE3_CMDUEST_DEMAND_IFILL_RF_MSB 68
#define DIAG_SBOX_MODE3_CMDUEST_PF_FILL_IFILL_RF_LSB 69
#define DIAG_SBOX_MODE3_CMDUEST_PF_FILL_IFILL_RF_MSB 69
#define DIAG_SBOX_MODE3_CMDUEST_PF_NO_FILL_IFILL_RF_LSB 70
#define DIAG_SBOX_MODE3_CMDUEST_PF_NO_FILL_IFILL_RF_MSB 70
#define DIAG_SBOX_MODE3_IRET_EX1_LSB 71
#define DIAG_SBOX_MODE3_IRET_EX1_MSB 71
#define DIAG_SBOX_MODE3_ICOH_EX1_LSB 72
#define DIAG_SBOX_MODE3_ICOH_EX1_MSB 72
#define DIAG_SBOX_MODE3_PF_PROMOTE_RF_LSB 73
#define DIAG_SBOX_MODE3_PF_PROMOTE_RF_MSB 73
#define DIAG_SBOX_MODE3_INTERRUPT_CRITICAL_SECTION_EX1_LSB 74
#define DIAG_SBOX_MODE3_INTERRUPT_CRITICAL_SECTION_EX1_MSB 74
#define DIAG_SBOX_MODE3_WRITE_NETWORK_UDN_D1_LSB 75
#define DIAG_SBOX_MODE3_WRITE_NETWORK_UDN_D1_MSB 75
#define DIAG_SBOX_MODE3_WRITE_NETWORK_IDN_D1_LSB 76
#define DIAG_SBOX_MODE3_WRITE_NETWORK_IDN_D1_MSB 76
#define DIAG_SBOX_MODE3_WRITE_NETWORK_SN_D1_LSB 77
#define DIAG_SBOX_MODE3_WRITE_NETWORK_SN_D1_MSB 77
#define DIAG_SBOX_MODE3_WRITE_CONFIRMED_P0_EX2_LSB 78
#define DIAG_SBOX_MODE3_WRITE_CONFIRMED_P0_EX2_MSB 78
#define DIAG_SBOX_MODE3_WRITE_CONFIRMED_P1_EX2_LSB 79
#define DIAG_SBOX_MODE3_WRITE_CONFIRMED_P1_EX2_MSB 79
#define DIAG_SBOX_MODE3_WRITE_CONFIRMED_P2_EX2_LSB 80
#define DIAG_SBOX_MODE3_WRITE_CONFIRMED_P2_EX2_MSB 80
#define DIAG_SBOX_MODE3_MTSPR_EX0_LSB 81
#define DIAG_SBOX_MODE3_MTSPR_EX0_MSB 81
#define DIAG_SBOX_MODE3_CPL_RF_LSB 82
#define DIAG_SBOX_MODE3_CPL_RF_MSB 83
#define DIAG_SBOX_MODE3_REG_IDENT_SRC_A_P0_RF_LSB 84
#define DIAG_SBOX_MODE3_REG_IDENT_SRC_A_P0_RF_MSB 89
#define DIAG_SBOX_MODE3_REG_IDENT_SRC_B_P0_RF_LSB 90
#define DIAG_SBOX_MODE3_REG_IDENT_SRC_B_P0_RF_MSB 95
#define DIAG_SBOX_MODE3_REG_IDENT_SRC_C_P0_RF_LSB 96
#define DIAG_SBOX_MODE3_REG_IDENT_SRC_C_P0_RF_MSB 101
#define DIAG_SBOX_MODE3_REG_IDENT_SRC_A_P1_RF_LSB 102
#define DIAG_SBOX_MODE3_REG_IDENT_SRC_A_P1_RF_MSB 107
#define DIAG_SBOX_MODE3_REG_IDENT_SRC_B_P1_RF_LSB 108
#define DIAG_SBOX_MODE3_REG_IDENT_SRC_B_P1_RF_MSB 113
#define DIAG_SBOX_MODE3_REG_IDENT_SRC_A_P2_RF_LSB 114
#define DIAG_SBOX_MODE3_REG_IDENT_SRC_A_P2_RF_MSB 119
#define DIAG_SBOX_MODE3_REG_IDENT_SRC_B_P2_RF_LSB 120
#define DIAG_SBOX_MODE3_REG_IDENT_SRC_B_P2_RF_MSB 125
#define DIAG_SBOX_MODE3_REG_IDENT_DEST_P0_EX0_LSB 126
#define DIAG_SBOX_MODE3_REG_IDENT_DEST_P0_EX0_MSB 131
#define DIAG_SBOX_MODE3_REG_IDENT_DEST_P1_EX0_LSB 132
#define DIAG_SBOX_MODE3_REG_IDENT_DEST_P1_EX0_MSB 137
#define DIAG_SBOX_MODE3_REG_IDENT_DEST_P2_EX0_LSB 138
#define DIAG_SBOX_MODE3_REG_IDENT_DEST_P2_EX0_MSB 143

#define DIAG_SBOX_MODE2_BYTES 8

#define DIAG_SBOX_MODE1_BYTES 2

#define DIAG_SBOX_MODE0_BYTES 0


#define DIAG_MBOX_WIDTH 144

#define DIAG_MBOX_MODE1_BYTES 1

#define DIAG_MBOX_MODE2_BYTES 8

#define DIAG_MBOX_MODE3_BYTES 18
#define DIAG_MBOX_MODE3_MEM_OPCODE_LSB 0
#define DIAG_MBOX_MODE3_MEM_OPCODE_MSB 3
#define DIAG_MBOX_MODE3_TLB_HIT_LSB 4
#define DIAG_MBOX_MODE3_TLB_HIT_MSB 4
#define DIAG_MBOX_MODE3_TLB_EXC_LSB 5
#define DIAG_MBOX_MODE3_TLB_EXC_MSB 5
#define DIAG_MBOX_MODE3_TLB_WRITEABLE_LSB 6
#define DIAG_MBOX_MODE3_TLB_WRITEABLE_MSB 6
#define DIAG_MBOX_MODE3_HIT_LSB 7
#define DIAG_MBOX_MODE3_HIT_MSB 7
#define DIAG_MBOX_MODE3_OPCODE_FIN_LSB 8
#define DIAG_MBOX_MODE3_OPCODE_FIN_MSB 11
#define DIAG_MBOX_MODE3_PREHIT1_LSB 12
#define DIAG_MBOX_MODE3_PREHIT1_MSB 12
#define DIAG_MBOX_MODE3_PREHIT0_LSB 13
#define DIAG_MBOX_MODE3_PREHIT0_MSB 13
#define DIAG_MBOX_MODE3_SET_OVLD_LSB 14
#define DIAG_MBOX_MODE3_SET_OVLD_MSB 14
#define DIAG_MBOX_MODE3_WAY0_STATE_LSB 15
#define DIAG_MBOX_MODE3_WAY0_STATE_MSB 16
#define DIAG_MBOX_MODE3_WAY1_STATE_LSB 17
#define DIAG_MBOX_MODE3_WAY1_STATE_MSB 18
#define DIAG_MBOX_MODE3_MRU_LSB 19
#define DIAG_MBOX_MODE3_MRU_MSB 19
#define DIAG_MBOX_MODE3_FILL_WAY_LSB 20
#define DIAG_MBOX_MODE3_FILL_WAY_MSB 20
#define DIAG_MBOX_MODE3_DMA_VALID_LSB 21
#define DIAG_MBOX_MODE3_DMA_VALID_MSB 21
#define DIAG_MBOX_MODE3_DMA_CMD_LSB 22
#define DIAG_MBOX_MODE3_DMA_CMD_MSB 22
#define DIAG_MBOX_MODE3_TLB_PA_LSB 23
#define DIAG_MBOX_MODE3_TLB_PA_MSB 58
#define DIAG_MBOX_MODE3_OP_SRC_B_LSB 59
#define DIAG_MBOX_MODE3_OP_SRC_B_MSB 90
#define DIAG_MBOX_MODE3_OP_SRC_A_LSB 91
#define DIAG_MBOX_MODE3_OP_SRC_A_MSB 122
#define DIAG_MBOX_MODE3_DMA_RD_FIFO_LSB 123
#define DIAG_MBOX_MODE3_DMA_RD_FIFO_MSB 124
#define DIAG_MBOX_MODE3_DMA_RD_BLK_LSB 125
#define DIAG_MBOX_MODE3_DMA_RD_BLK_MSB 125
#define DIAG_MBOX_MODE3_DMA_BUF_WR_LSB 126
#define DIAG_MBOX_MODE3_DMA_BUF_WR_MSB 126
#define DIAG_MBOX_MODE3_DMA_ENGINE_STATE_LSB 127
#define DIAG_MBOX_MODE3_DMA_ENGINE_STATE_MSB 128
#define DIAG_MBOX_MODE3_DMA_LOAD_STATE_LSB 129
#define DIAG_MBOX_MODE3_DMA_LOAD_STATE_MSB 130
#define DIAG_MBOX_MODE3_DMA_ST_STATE_LSB 131
#define DIAG_MBOX_MODE3_DMA_ST_STATE_MSB 132
#define DIAG_MBOX_MODE3_DMA_BLOCK_STATE_LSB 133
#define DIAG_MBOX_MODE3_DMA_BLOCK_STATE_MSB 136

#define DIAG_MBOX_MODE0_BYTES 0


#define DIAG_CBOX_WIDTH 144

#define DIAG_CBOX_MODE1_BYTES 1

#define DIAG_CBOX_MODE2_BYTES 8

#define DIAG_CBOX_MODE3_BYTES 18
#define DIAG_CBOX_MODE3_ARB_CMD_LSB 0
#define DIAG_CBOX_MODE3_ARB_CMD_MSB 3
#define DIAG_CBOX_MODE3_REJECT_LSB 4
#define DIAG_CBOX_MODE3_REJECT_MSB 4
#define DIAG_CBOX_MODE3_HIT1_LSB 5
#define DIAG_CBOX_MODE3_HIT1_MSB 5
#define DIAG_CBOX_MODE3_HIT0_LSB 6
#define DIAG_CBOX_MODE3_HIT0_MSB 6
#define DIAG_CBOX_MODE3_STALL_ISSUE_LSB 7
#define DIAG_CBOX_MODE3_STALL_ISSUE_MSB 7
#define DIAG_CBOX_MODE3_REJECT_VEC_LSB 8
#define DIAG_CBOX_MODE3_REJECT_VEC_MSB 17
#define DIAG_CBOX_MODE3_ARB_SEL_LSB 18
#define DIAG_CBOX_MODE3_ARB_SEL_MSB 22
#define DIAG_CBOX_MODE3_ARB_CMD_LSB 23
#define DIAG_CBOX_MODE3_ARB_CMD_MSB 27
#define DIAG_CBOX_MODE3_MAF_MATCH_LSB 28
#define DIAG_CBOX_MODE3_MAF_MATCH_MSB 28
#define DIAG_CBOX_MODE3_WRITE_RTF_LSB 29
#define DIAG_CBOX_MODE3_WRITE_RTF_MSB 29
#define DIAG_CBOX_MODE3_DEALLOC_MAF_LSB 30
#define DIAG_CBOX_MODE3_DEALLOC_MAF_MSB 30
#define DIAG_CBOX_MODE3_ALLOC_MAF_LSB 31
#define DIAG_CBOX_MODE3_ALLOC_MAF_MSB 31
#define DIAG_CBOX_MODE3_UPDATE_MAF_LSB 32
#define DIAG_CBOX_MODE3_UPDATE_MAF_MSB 32
#define DIAG_CBOX_MODE3_DMA_CMD_LSB 33
#define DIAG_CBOX_MODE3_DMA_CMD_MSB 33
#define DIAG_CBOX_MODE3_DMA_VAL_LSB 34
#define DIAG_CBOX_MODE3_DMA_VAL_MSB 34
#define DIAG_CBOX_MODE3_FILL_PARITY_ERROR_LSB 35
#define DIAG_CBOX_MODE3_FILL_PARITY_ERROR_MSB 35
#define DIAG_CBOX_MODE3_IFILL_ERR_LSB 36
#define DIAG_CBOX_MODE3_IFILL_ERR_MSB 36
#define DIAG_CBOX_MODE3_WAY1_STATE_LSB 37
#define DIAG_CBOX_MODE3_WAY1_STATE_MSB 38
#define DIAG_CBOX_MODE3_WAY0_STATE_LSB 39
#define DIAG_CBOX_MODE3_WAY0_STATE_MSB 40
#define DIAG_CBOX_MODE3_FILL_CMD_LSB 41
#define DIAG_CBOX_MODE3_FILL_CMD_MSB 44
#define DIAG_CBOX_MODE3_EG_CMD_OP_LSB 45
#define DIAG_CBOX_MODE3_EG_CMD_OP_MSB 47
#define DIAG_CBOX_MODE3_TDN_CMD_VLD_LSB 48
#define DIAG_CBOX_MODE3_TDN_CMD_VLD_MSB 48
#define DIAG_CBOX_MODE3_MDN_DAT_WREN_LSB 49
#define DIAG_CBOX_MODE3_MDN_DAT_WREN_MSB 49
#define DIAG_CBOX_MODE3_MDN_CMD_WREN_LSB 50
#define DIAG_CBOX_MODE3_MDN_CMD_WREN_MSB 50
#define DIAG_CBOX_MODE3_FILL_WRITES_TAG_LSB 51
#define DIAG_CBOX_MODE3_FILL_WRITES_TAG_MSB 51
#define DIAG_CBOX_MODE3_RD_VLD_LSB 52
#define DIAG_CBOX_MODE3_RD_VLD_MSB 52
#define DIAG_CBOX_MODE3_IFILL_RTN_LSB 53
#define DIAG_CBOX_MODE3_IFILL_RTN_MSB 53
#define DIAG_CBOX_MODE3_DEC_RTF_LSB 54
#define DIAG_CBOX_MODE3_DEC_RTF_MSB 54
#define DIAG_CBOX_MODE3_INC_RTF_LSB 55
#define DIAG_CBOX_MODE3_INC_RTF_MSB 55
#define DIAG_CBOX_MODE3_SPCL_STATE_LSB 56
#define DIAG_CBOX_MODE3_SPCL_STATE_MSB 61
#define DIAG_CBOX_MODE3_DEST_REG_LSB 62
#define DIAG_CBOX_MODE3_DEST_REG_MSB 67
#define DIAG_CBOX_MODE3_RAM_CTL_LSB 68
#define DIAG_CBOX_MODE3_RAM_CTL_MSB 75
#define DIAG_CBOX_MODE3_MISS_INFO_LSB 76
#define DIAG_CBOX_MODE3_MISS_INFO_MSB 87
#define DIAG_CBOX_MODE3_MAF_CNT_LSB 88
#define DIAG_CBOX_MODE3_MAF_CNT_MSB 91
#define DIAG_CBOX_MODE3_RTF_CNT_LSB 92
#define DIAG_CBOX_MODE3_RTF_CNT_MSB 97
#define DIAG_CBOX_MODE3_MAF_CMD_LSB 98
#define DIAG_CBOX_MODE3_MAF_CMD_MSB 101
#define DIAG_CBOX_MODE3_MAF_CMD_IS_SNOOP_LSB 102
#define DIAG_CBOX_MODE3_MAF_CMD_IS_SNOOP_MSB 102
#define DIAG_CBOX_MODE3_STARVATION_STATUS_LSB 103
#define DIAG_CBOX_MODE3_STARVATION_STATUS_MSB 107
#define DIAG_CBOX_MODE3_C2_PA_LSB 108
#define DIAG_CBOX_MODE3_C2_PA_MSB 143

#define DIAG_CBOX_MODE0_BYTES 0


#define DIAG_STN_WIDTH 80

#define DIAG_STN_MODE1_BYTES 1

#define DIAG_STN_MODE2_BYTES 4

#define DIAG_STN_MODE3_BYTES 10
#define DIAG_STN_MODE3_IPORT_READY_LSB 0
#define DIAG_STN_MODE3_IPORT_READY_MSB 4
#define DIAG_STN_MODE3_OFIFO_ADVANCE_LSB 5
#define DIAG_STN_MODE3_OFIFO_ADVANCE_MSB 5
#define DIAG_STN_MODE3_ROUTE_ADVANCE_LSB 6
#define DIAG_STN_MODE3_ROUTE_ADVANCE_MSB 6
#define DIAG_STN_MODE3_FREEZE_PROC_LSB 7
#define DIAG_STN_MODE3_FREEZE_PROC_MSB 7
#define DIAG_STN_MODE3_IFIFO_ADVANCE_LSB 8
#define DIAG_STN_MODE3_IFIFO_ADVANCE_MSB 12
#define DIAG_STN_MODE3_OFIFO_READY_LSB 13
#define DIAG_STN_MODE3_OFIFO_READY_MSB 17
#define DIAG_STN_MODE3_EX0_PC_LSB 18
#define DIAG_STN_MODE3_EX0_PC_MSB 48
#define DIAG_STN_MODE3_ISOURCE_LSB 49
#define DIAG_STN_MODE3_ISOURCE_MSB 66
#define DIAG_STN_MODE3_IMISS_LSB 67
#define DIAG_STN_MODE3_IMISS_MSB 67
#define DIAG_STN_MODE3_EXCEPTION_LSB 68
#define DIAG_STN_MODE3_EXCEPTION_MSB 74
#define DIAG_STN_MODE3_FREEZE_LSB 75
#define DIAG_STN_MODE3_FREEZE_MSB 75
#define DIAG_STN_MODE3_RESTART_LSB 76
#define DIAG_STN_MODE3_RESTART_MSB 76
#define DIAG_STN_MODE3_IF_VLD_LSB 77
#define DIAG_STN_MODE3_IF_VLD_MSB 77
#define DIAG_STN_MODE3_ID_VLD_LSB 78
#define DIAG_STN_MODE3_ID_VLD_MSB 78
#define DIAG_STN_MODE3_EX_VLD_LSB 79
#define DIAG_STN_MODE3_EX_VLD_MSB 79

#define DIAG_STN_MODE0_BYTES 0


#define DIAG_XDN_WIDTH 104

#define DIAG_XDN_MODE3_BYTES 13
#define DIAG_XDN_MODE3_UDN_CORE_EGR_LSB 0
#define DIAG_XDN_MODE3_UDN_CORE_EGR_MSB 0
#define DIAG_XDN_MODE3_IDN_CORE_EGR_LSB 1
#define DIAG_XDN_MODE3_IDN_CORE_EGR_MSB 1
#define DIAG_XDN_MODE3_MDN_CORE_EGR_LSB 2
#define DIAG_XDN_MODE3_MDN_CORE_EGR_MSB 2
#define DIAG_XDN_MODE3_TDN_CORE_EGR_LSB 3
#define DIAG_XDN_MODE3_TDN_CORE_EGR_MSB 3
#define DIAG_XDN_MODE3_UDN_CORE_ING_LSB 4
#define DIAG_XDN_MODE3_UDN_CORE_ING_MSB 4
#define DIAG_XDN_MODE3_IDN_CORE_ING_LSB 5
#define DIAG_XDN_MODE3_IDN_CORE_ING_MSB 5
#define DIAG_XDN_MODE3_MDN_CORE_ING_LSB 6
#define DIAG_XDN_MODE3_MDN_CORE_ING_MSB 6
#define DIAG_XDN_MODE3_TDN_CORE_ING_LSB 7
#define DIAG_XDN_MODE3_TDN_CORE_ING_MSB 7
#define DIAG_XDN_MODE3_UDN_COMP_EGR_LSB 8
#define DIAG_XDN_MODE3_UDN_COMP_EGR_MSB 11
#define DIAG_XDN_MODE3_IDN_COMP_EGR_LSB 12
#define DIAG_XDN_MODE3_IDN_COMP_EGR_MSB 15
#define DIAG_XDN_MODE3_MDN_COMP_EGR_LSB 16
#define DIAG_XDN_MODE3_MDN_COMP_EGR_MSB 19
#define DIAG_XDN_MODE3_TDN_COMP_EGR_LSB 20
#define DIAG_XDN_MODE3_TDN_COMP_EGR_MSB 23
#define DIAG_XDN_MODE3_UDN_COMP_ING_LSB 24
#define DIAG_XDN_MODE3_UDN_COMP_ING_MSB 27
#define DIAG_XDN_MODE3_IDN_COMP_ING_LSB 28
#define DIAG_XDN_MODE3_IDN_COMP_ING_MSB 31
#define DIAG_XDN_MODE3_MDN_COMP_ING_LSB 32
#define DIAG_XDN_MODE3_MDN_COMP_ING_MSB 35
#define DIAG_XDN_MODE3_TDN_COMP_ING_LSB 36
#define DIAG_XDN_MODE3_TDN_COMP_ING_MSB 39
#define DIAG_XDN_MODE3_UDN_SOP_LSB 40
#define DIAG_XDN_MODE3_UDN_SOP_MSB 44
#define DIAG_XDN_MODE3_IDN_SOP_LSB 45
#define DIAG_XDN_MODE3_IDN_SOP_MSB 49
#define DIAG_XDN_MODE3_MDN_SOP_LSB 50
#define DIAG_XDN_MODE3_MDN_SOP_MSB 54
#define DIAG_XDN_MODE3_TDN_SOP_LSB 55
#define DIAG_XDN_MODE3_TDN_SOP_MSB 59
#define DIAG_XDN_MODE3_UDN_CRED_LSB 60
#define DIAG_XDN_MODE3_UDN_CRED_MSB 67
#define DIAG_XDN_MODE3_IDN_CRED_LSB 68
#define DIAG_XDN_MODE3_IDN_CRED_MSB 75
#define DIAG_XDN_MODE3_MDN_CRED_LSB 76
#define DIAG_XDN_MODE3_MDN_CRED_MSB 83
#define DIAG_XDN_MODE3_TDN_CRED_LSB 84
#define DIAG_XDN_MODE3_TDN_CRED_MSB 91
#define DIAG_XDN_MODE3_UDN_DMX_STALL_LSB 92
#define DIAG_XDN_MODE3_UDN_DMX_STALL_MSB 92
#define DIAG_XDN_MODE3_IDN_DMX_STALL_LSB 93
#define DIAG_XDN_MODE3_IDN_DMX_STALL_MSB 93
#define DIAG_XDN_MODE3_UDN_DMX_Q_AVAIL_LSB 94
#define DIAG_XDN_MODE3_UDN_DMX_Q_AVAIL_MSB 98
#define DIAG_XDN_MODE3_IDN_DMX_Q_AVAIL_LSB 99
#define DIAG_XDN_MODE3_IDN_DMX_Q_AVAIL_MSB 101

#define DIAG_XDN_MODE2_BYTES 3

#define DIAG_XDN_MODE1_BYTES 1

#define DIAG_XDN_MODE0_BYTES 0



#define DIAG_TOP_EVENTS 6
#define DIAG_TOP_PERF_EVENTS 6

#define DIAG_TOP_EVENT_ZERO_VEC_BIT 0
#define DIAG_TOP_EVENT_ZERO 0
#define DIAG_TOP_EVENT_ONE_VEC_BIT 1
#define DIAG_TOP_EVENT_ONE 1
#define DIAG_TOP_EVENT_PASS_WRITTEN_VEC_BIT 2
#define DIAG_TOP_EVENT_PASS_WRITTEN 2
#define DIAG_TOP_EVENT_FAIL_WRITTEN_VEC_BIT 3
#define DIAG_TOP_EVENT_FAIL_WRITTEN 3
#define DIAG_TOP_EVENT_DONE_WRITTEN_VEC_BIT 4
#define DIAG_TOP_EVENT_DONE_WRITTEN 4
#define DIAG_TOP_EVENT_QUIESCED_VEC_BIT 5
#define DIAG_TOP_EVENT_QUIESCED 5

#define DIAG_SBOX_EVENTS 18
#define DIAG_SBOX_PERF_EVENTS 18

#define DIAG_SBOX_EVENT_MP_BUNDLE_RETIRED_VEC_BIT 0
#define DIAG_SBOX_EVENT_MP_BUNDLE_RETIRED 6
#define DIAG_SBOX_EVENT_MP_BUNDLE_1_INSTR_RETIRED_VEC_BIT 1
#define DIAG_SBOX_EVENT_MP_BUNDLE_1_INSTR_RETIRED 7
#define DIAG_SBOX_EVENT_MP_BUNDLE_2_INSTR_RETIRED_VEC_BIT 2
#define DIAG_SBOX_EVENT_MP_BUNDLE_2_INSTR_RETIRED 8
#define DIAG_SBOX_EVENT_MP_BUNDLE_3_INSTR_RETIRED_VEC_BIT 3
#define DIAG_SBOX_EVENT_MP_BUNDLE_3_INSTR_RETIRED 9
#define DIAG_SBOX_EVENT_MP_UDN_READ_STALL_VEC_BIT 4
#define DIAG_SBOX_EVENT_MP_UDN_READ_STALL 10
#define DIAG_SBOX_EVENT_MP_IDN_READ_STALL_VEC_BIT 5
#define DIAG_SBOX_EVENT_MP_IDN_READ_STALL 11
#define DIAG_SBOX_EVENT_MP_SN_READ_STALL_VEC_BIT 6
#define DIAG_SBOX_EVENT_MP_SN_READ_STALL 12
#define DIAG_SBOX_EVENT_MP_UDN_WRITE_STALL_VEC_BIT 7
#define DIAG_SBOX_EVENT_MP_UDN_WRITE_STALL 13
#define DIAG_SBOX_EVENT_MP_IDN_WRITE_STALL_VEC_BIT 8
#define DIAG_SBOX_EVENT_MP_IDN_WRITE_STALL 14
#define DIAG_SBOX_EVENT_MP_SN_WRITE_STALL_VEC_BIT 9
#define DIAG_SBOX_EVENT_MP_SN_WRITE_STALL 15
#define DIAG_SBOX_EVENT_MP_DATA_CACHE_STALL_VEC_BIT 10
#define DIAG_SBOX_EVENT_MP_DATA_CACHE_STALL 16
#define DIAG_SBOX_EVENT_MP_INSTRUCTION_CACHE_STALL_VEC_BIT 11
#define DIAG_SBOX_EVENT_MP_INSTRUCTION_CACHE_STALL 17
#define DIAG_SBOX_EVENT_MP_ICACHE_HIT_ISSUED_VEC_BIT 12
#define DIAG_SBOX_EVENT_MP_ICACHE_HIT_ISSUED 18
#define DIAG_SBOX_EVENT_MP_ITLB_HIT_ISSUED_VEC_BIT 13
#define DIAG_SBOX_EVENT_MP_ITLB_HIT_ISSUED 19
#define DIAG_SBOX_EVENT_MP_CONDITIONAL_BRANCH_MISSPREDICT_VEC_BIT 14
#define DIAG_SBOX_EVENT_MP_CONDITIONAL_BRANCH_MISSPREDICT 20
#define DIAG_SBOX_EVENT_MP_INDIRECT_BRANCH_MISSPREDICT_VEC_BIT 15
#define DIAG_SBOX_EVENT_MP_INDIRECT_BRANCH_MISSPREDICT 21
#define DIAG_SBOX_EVENT_MP_CONDITIONAL_BRANCH_ISSUED_VEC_BIT 16
#define DIAG_SBOX_EVENT_MP_CONDITIONAL_BRANCH_ISSUED 22
#define DIAG_SBOX_EVENT_MP_INDIRECT_BRANCH_ISSUED_VEC_BIT 17
#define DIAG_SBOX_EVENT_MP_INDIRECT_BRANCH_ISSUED 23

#define DIAG_MBOX_EVENTS 3
#define DIAG_MBOX_PERF_EVENTS 3

#define DIAG_MBOX_EVENT_TLB_HIT_VEC_BIT 0
#define DIAG_MBOX_EVENT_TLB_HIT 24
#define DIAG_MBOX_EVENT_TLB_EXC_VEC_BIT 1
#define DIAG_MBOX_EVENT_TLB_EXC 25
#define DIAG_MBOX_EVENT_HIT_VEC_BIT 2
#define DIAG_MBOX_EVENT_HIT 26

#define DIAG_CBOX_EVENTS 19
#define DIAG_CBOX_PERF_EVENTS 19

#define DIAG_CBOX_EVENT_MEM_CMD_RD_VEC_BIT 0
#define DIAG_CBOX_EVENT_MEM_CMD_RD 27
#define DIAG_CBOX_EVENT_MEM_CMD_WR_VEC_BIT 1
#define DIAG_CBOX_EVENT_MEM_CMD_WR 28
#define DIAG_CBOX_EVENT_MEM_CMD_VIC_VEC_BIT 2
#define DIAG_CBOX_EVENT_MEM_CMD_VIC 29
#define DIAG_CBOX_EVENT_MISS_I_VEC_BIT 3
#define DIAG_CBOX_EVENT_MISS_I 30
#define DIAG_CBOX_EVENT_MISS_D_WR_VEC_BIT 4
#define DIAG_CBOX_EVENT_MISS_D_WR 31
#define DIAG_CBOX_EVENT_MISS_D_RD_VEC_BIT 5
#define DIAG_CBOX_EVENT_MISS_D_RD 32
#define DIAG_CBOX_EVENT_MISS_TDN_VEC_BIT 6
#define DIAG_CBOX_EVENT_MISS_TDN 33
#define DIAG_CBOX_EVENT_OLOC_CMD_RD_VEC_BIT 7
#define DIAG_CBOX_EVENT_OLOC_CMD_RD 34
#define DIAG_CBOX_EVENT_OLOC_CMD_WR_VEC_BIT 8
#define DIAG_CBOX_EVENT_OLOC_CMD_WR 35
#define DIAG_CBOX_EVENT_TDN_REC_RD_VEC_BIT 9
#define DIAG_CBOX_EVENT_TDN_REC_RD 36
#define DIAG_CBOX_EVENT_TDN_REC_WR_VEC_BIT 10
#define DIAG_CBOX_EVENT_TDN_REC_WR 37
#define DIAG_CBOX_EVENT_L2_HIT_VEC_BIT 11
#define DIAG_CBOX_EVENT_L2_HIT 38
#define DIAG_CBOX_EVENT_L2_INV_VEC_BIT 12
#define DIAG_CBOX_EVENT_L2_INV 39
#define DIAG_CBOX_EVENT_TDN_STARVED_VEC_BIT 13
#define DIAG_CBOX_EVENT_TDN_STARVED 40
#define DIAG_CBOX_EVENT_DMA_STARVED_VEC_BIT 14
#define DIAG_CBOX_EVENT_DMA_STARVED 41
#define DIAG_CBOX_EVENT_MDN_STARVED_VEC_BIT 15
#define DIAG_CBOX_EVENT_MDN_STARVED 42
#define DIAG_CBOX_EVENT_RTF_STARVED_VEC_BIT 16
#define DIAG_CBOX_EVENT_RTF_STARVED 43
#define DIAG_CBOX_EVENT_IREQ_STARVED_VEC_BIT 17
#define DIAG_CBOX_EVENT_IREQ_STARVED 44
#define DIAG_CBOX_EVENT_RRTF_STARVED_VEC_BIT 18
#define DIAG_CBOX_EVENT_RRTF_STARVED 45

#define DIAG_STN_EVENTS 16
#define DIAG_STN_PERF_EVENTS 16

#define DIAG_STN_EVENT_INST_EXEC_VEC_BIT 0
#define DIAG_STN_EVENT_INST_EXEC 46
#define DIAG_STN_EVENT_N_OVALID_VEC_BIT 1
#define DIAG_STN_EVENT_N_OVALID 47
#define DIAG_STN_EVENT_E_OVALID_VEC_BIT 2
#define DIAG_STN_EVENT_E_OVALID 48
#define DIAG_STN_EVENT_S_OVALID_VEC_BIT 3
#define DIAG_STN_EVENT_S_OVALID 49
#define DIAG_STN_EVENT_W_OVALID_VEC_BIT 4
#define DIAG_STN_EVENT_W_OVALID 50
#define DIAG_STN_EVENT_M_OVALID_VEC_BIT 5
#define DIAG_STN_EVENT_M_OVALID 51
#define DIAG_STN_EVENT_N_OSTALL_VEC_BIT 6
#define DIAG_STN_EVENT_N_OSTALL 52
#define DIAG_STN_EVENT_E_OSTALL_VEC_BIT 7
#define DIAG_STN_EVENT_E_OSTALL 53
#define DIAG_STN_EVENT_S_OSTALL_VEC_BIT 8
#define DIAG_STN_EVENT_S_OSTALL 54
#define DIAG_STN_EVENT_W_OSTALL_VEC_BIT 9
#define DIAG_STN_EVENT_W_OSTALL 55
#define DIAG_STN_EVENT_M_OSTALL_VEC_BIT 10
#define DIAG_STN_EVENT_M_OSTALL 56
#define DIAG_STN_EVENT_N_ISTALL_VEC_BIT 11
#define DIAG_STN_EVENT_N_ISTALL 57
#define DIAG_STN_EVENT_E_ISTALL_VEC_BIT 12
#define DIAG_STN_EVENT_E_ISTALL 58
#define DIAG_STN_EVENT_S_ISTALL_VEC_BIT 13
#define DIAG_STN_EVENT_S_ISTALL 59
#define DIAG_STN_EVENT_W_ISTALL_VEC_BIT 14
#define DIAG_STN_EVENT_W_ISTALL 60
#define DIAG_STN_EVENT_M_ISTALL_VEC_BIT 15
#define DIAG_STN_EVENT_M_ISTALL 61

#define DIAG_XDN_EVENTS 30
#define DIAG_XDN_PERF_EVENTS 30

#define DIAG_XDN_EVENT_UDN_SNT_C_VEC_BIT 0
#define DIAG_XDN_EVENT_UDN_SNT_C 62
#define DIAG_XDN_EVENT_UDN_RCVD_C_VEC_BIT 1
#define DIAG_XDN_EVENT_UDN_RCVD_C 63
#define DIAG_XDN_EVENT_UDN_SNT_N_VEC_BIT 2
#define DIAG_XDN_EVENT_UDN_SNT_N 64
#define DIAG_XDN_EVENT_UDN_SNT_S_VEC_BIT 3
#define DIAG_XDN_EVENT_UDN_SNT_S 65
#define DIAG_XDN_EVENT_UDN_SNT_E_VEC_BIT 4
#define DIAG_XDN_EVENT_UDN_SNT_E 66
#define DIAG_XDN_EVENT_UDN_SNT_W_VEC_BIT 5
#define DIAG_XDN_EVENT_UDN_SNT_W 67
#define DIAG_XDN_EVENT_UDN_BUBBLE_ANY_VEC_BIT 6
#define DIAG_XDN_EVENT_UDN_BUBBLE_ANY 68
#define DIAG_XDN_EVENT_IDN_SNT_C_VEC_BIT 7
#define DIAG_XDN_EVENT_IDN_SNT_C 69
#define DIAG_XDN_EVENT_IDN_RCVD_C_VEC_BIT 8
#define DIAG_XDN_EVENT_IDN_RCVD_C 70
#define DIAG_XDN_EVENT_IDN_SNT_N_VEC_BIT 9
#define DIAG_XDN_EVENT_IDN_SNT_N 71
#define DIAG_XDN_EVENT_IDN_SNT_S_VEC_BIT 10
#define DIAG_XDN_EVENT_IDN_SNT_S 72
#define DIAG_XDN_EVENT_IDN_SNT_E_VEC_BIT 11
#define DIAG_XDN_EVENT_IDN_SNT_E 73
#define DIAG_XDN_EVENT_IDN_SNT_W_VEC_BIT 12
#define DIAG_XDN_EVENT_IDN_SNT_W 74
#define DIAG_XDN_EVENT_IDN_BUBBLE_ANY_VEC_BIT 13
#define DIAG_XDN_EVENT_IDN_BUBBLE_ANY 75
#define DIAG_XDN_EVENT_MDN_SNT_C_VEC_BIT 14
#define DIAG_XDN_EVENT_MDN_SNT_C 76
#define DIAG_XDN_EVENT_MDN_RCVD_C_VEC_BIT 15
#define DIAG_XDN_EVENT_MDN_RCVD_C 77
#define DIAG_XDN_EVENT_MDN_SNT_N_VEC_BIT 16
#define DIAG_XDN_EVENT_MDN_SNT_N 78
#define DIAG_XDN_EVENT_MDN_SNT_S_VEC_BIT 17
#define DIAG_XDN_EVENT_MDN_SNT_S 79
#define DIAG_XDN_EVENT_MDN_SNT_E_VEC_BIT 18
#define DIAG_XDN_EVENT_MDN_SNT_E 80
#define DIAG_XDN_EVENT_MDN_SNT_W_VEC_BIT 19
#define DIAG_XDN_EVENT_MDN_SNT_W 81
#define DIAG_XDN_EVENT_MDN_BUBBLE_ANY_VEC_BIT 20
#define DIAG_XDN_EVENT_MDN_BUBBLE_ANY 82
#define DIAG_XDN_EVENT_TDN_SNT_C_VEC_BIT 21
#define DIAG_XDN_EVENT_TDN_SNT_C 83
#define DIAG_XDN_EVENT_TDN_RCVD_C_VEC_BIT 22
#define DIAG_XDN_EVENT_TDN_RCVD_C 84
#define DIAG_XDN_EVENT_TDN_SNT_N_VEC_BIT 23
#define DIAG_XDN_EVENT_TDN_SNT_N 85
#define DIAG_XDN_EVENT_TDN_SNT_S_VEC_BIT 24
#define DIAG_XDN_EVENT_TDN_SNT_S 86
#define DIAG_XDN_EVENT_TDN_SNT_E_VEC_BIT 25
#define DIAG_XDN_EVENT_TDN_SNT_E 87
#define DIAG_XDN_EVENT_TDN_SNT_W_VEC_BIT 26
#define DIAG_XDN_EVENT_TDN_SNT_W 88
#define DIAG_XDN_EVENT_TDN_BUBBLE_ANY_VEC_BIT 27
#define DIAG_XDN_EVENT_TDN_BUBBLE_ANY 89
#define DIAG_XDN_EVENT_UDN_DMUX_STALL_VEC_BIT 28
#define DIAG_XDN_EVENT_UDN_DMUX_STALL 90
#define DIAG_XDN_EVENT_IDN_DMUX_STALL_VEC_BIT 29
#define DIAG_XDN_EVENT_IDN_DMUX_STALL 91

// Events Added by Hand (not in diag.vh)

#define DIAG_EVENT_WATCH_REGISTER_MATCH 92
#define DIAG_EVENT_BROADCAST_WIRE_0 93
#define DIAG_EVENT_BROADCAST_WIRE_1 94
#define DIAG_EVENT_BROADCAST_WIRE_2 95
#define DIAG_EVENT_BROADCAST_WIRE_3 96
#define DIAG_EVENT_PERF_COUNT_0_OVERFLOW 97
#define DIAG_EVENT_PERF_COUNT_0_OVERFLOW 98

#endif // __MAESTRO_SPR_REGS_TILE49_H
